spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leasing?useSSL=false&serverTimezone=UTC&llowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/leasing?useSSL=false&serverTimezone=UTC&llowPublicKeyRetrieval=true
    user: user
    password: password
    baseline-on-migrate: true
    enabled: true
    sql-migration-prefix: V
    sql-migration-separator: __
    locations:
      - classpath:db/migration
    sql-migration-suffixes: .sql

server:
  port: 8000